modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/nitrodynamite18/DeeperAndDarkerNeoForge/issues"
[[mods]] #mandatory
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://github.com/nitrodynamite18/DeeperAndDarkerNeoForge"
    logoFile="banner.png"
    credits="${mod_credits}"
    authors="${mod_authors}"
    description='''${mod_description}'''
    config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
